name: Compile M3U files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: List M3U files
      run: |
        find . -name "*.m3u"

    - name: Print M3U file contents
      run: |
        find . -name "*.m3u" -exec cat {} +

    - name: Combine M3U files
      run: |
        find . -name "*.m3u" -exec cat {} + > combined.m3u8

    - name: Upload combined M3U file
      uses: actions/upload-artifact@v4
      with:
        name: combined-m3u8
        path: combined.m3u8
