name: Compile and Publish M3U files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Combine M3U files
      run: |
        find . -name "*.m3u" -exec cat {} + > combined.m3u8

    - name: Upload combined M3U file to GitHub Pages
      run: |
        mkdir -p out
        mv combined.m3u8 out/
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add out/combined.m3u8
        git commit -m 'Upload combined M3U file'
        git push origin `main:gh-pages`
